version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=futuro_funcionario
      - POSTGRES_PASSWORD=smartABC
      - POSTGRES_DB=abastecimento
    ports:
      - 5432:5432
    volumes:
      - ./data:/data/postgres